# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStation',
            fields=[
                ('base_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('region', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsumeterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level_reading', models.DecimalField(decimal_places=2, max_digits=5)),
                ('power_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumeter.BaseStation')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('base_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_set', to='insumeter.BaseStation')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumeter.Sensor'),
        ),
        migrations.AddField(
            model_name='basestation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_station_set', to='insumeter.InsumeterUser'),
        ),
    ]
