# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumeter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basestation',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
