# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insumeter', '0002_auto_20170328_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(default=datetime.datetime(2017, 3, 28, 12, 59, 28, 516394, tzinfo=utc))),
                ('level_reading', models.DecimalField(decimal_places=2, max_digits=4)),
                ('power_level', models.DecimalField(decimal_places=2, max_digits=4)),
                ('base_station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumeter.BaseStation')),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumeter.Sensor')),
            ],
        ),
        migrations.RemoveField(
            model_name='logs',
            name='base_station_id',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='sensor_id',
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
    ]
