# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumeter', '0002_auto_20170416_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='level_reading',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='log',
            name='power_level',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
