# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumeter', '0003_auto_20170328_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
