# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumeter', '0003_auto_20170416_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='base_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_set', to='insumeter.BaseStation'),
        ),
    ]
