# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumeter', '0004_auto_20170416_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='user',
        ),
    ]
