# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 04:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumeter', '0004_auto_20170403_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basestation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
