# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumeter', '0005_remove_log_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='base_station_id',
            new_name='base_id',
        ),
    ]
