# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumeter', '0005_auto_20170403_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basestation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumeter.InsumeterUser'),
        ),
    ]
