# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumeter', '0006_auto_20170416_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='base_id',
            new_name='base_station_id',
        ),
    ]
