# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumeter', '0007_auto_20170501_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='tank_height',
            field=models.DecimalField(decimal_places=2, default=34.54, max_digits=5),
            preserve_default=False,
        ),
    ]
